(cl:in-package f110_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAP_COUNT-VAL
          LAP_COUNT
          LAP_TIME-VAL
          LAP_TIME
          AVERAGE_LATERAL_ERROR_TO_GLOBAL_WAYPOINTS-VAL
          AVERAGE_LATERAL_ERROR_TO_GLOBAL_WAYPOINTS
          MAX_LATERAL_ERROR_TO_GLOBAL_WAYPOINTS-VAL
          MAX_LATERAL_ERROR_TO_GLOBAL_WAYPOINTS
))