# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from f110_msgs/OpponentTrajectory.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import f110_msgs.msg
import std_msgs.msg

class OpponentTrajectory(genpy.Message):
  _md5sum = "fe4d653bec85c82c41a017b9bdc2a6f1"
  _type = "f110_msgs/OpponentTrajectory"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float64 lap_count
bool opp_is_on_trajectory
OppWpnt[] oppwpnts
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: f110_msgs/OppWpnt
int32 id

# frenet coordinates
float64 s_m
float64 d_m

# map coordinates
float64 x_m
float64 y_m

# track information
float64 proj_vs_mps
float64 vd_mps

#variance  
float64 d_var
float64 vs_var

"""
  __slots__ = ['header','lap_count','opp_is_on_trajectory','oppwpnts']
  _slot_types = ['std_msgs/Header','float64','bool','f110_msgs/OppWpnt[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lap_count,opp_is_on_trajectory,oppwpnts

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OpponentTrajectory, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lap_count is None:
        self.lap_count = 0.
      if self.opp_is_on_trajectory is None:
        self.opp_is_on_trajectory = False
      if self.oppwpnts is None:
        self.oppwpnts = []
    else:
      self.header = std_msgs.msg.Header()
      self.lap_count = 0.
      self.opp_is_on_trajectory = False
      self.oppwpnts = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_dB().pack(_x.lap_count, _x.opp_is_on_trajectory))
      length = len(self.oppwpnts)
      buff.write(_struct_I.pack(length))
      for val1 in self.oppwpnts:
        _x = val1
        buff.write(_get_struct_i8d().pack(_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.proj_vs_mps, _x.vd_mps, _x.d_var, _x.vs_var))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.oppwpnts is None:
        self.oppwpnts = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.lap_count, _x.opp_is_on_trajectory,) = _get_struct_dB().unpack(str[start:end])
      self.opp_is_on_trajectory = bool(self.opp_is_on_trajectory)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.oppwpnts = []
      for i in range(0, length):
        val1 = f110_msgs.msg.OppWpnt()
        _x = val1
        start = end
        end += 68
        (_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.proj_vs_mps, _x.vd_mps, _x.d_var, _x.vs_var,) = _get_struct_i8d().unpack(str[start:end])
        self.oppwpnts.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_dB().pack(_x.lap_count, _x.opp_is_on_trajectory))
      length = len(self.oppwpnts)
      buff.write(_struct_I.pack(length))
      for val1 in self.oppwpnts:
        _x = val1
        buff.write(_get_struct_i8d().pack(_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.proj_vs_mps, _x.vd_mps, _x.d_var, _x.vs_var))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.oppwpnts is None:
        self.oppwpnts = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.lap_count, _x.opp_is_on_trajectory,) = _get_struct_dB().unpack(str[start:end])
      self.opp_is_on_trajectory = bool(self.opp_is_on_trajectory)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.oppwpnts = []
      for i in range(0, length):
        val1 = f110_msgs.msg.OppWpnt()
        _x = val1
        start = end
        end += 68
        (_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.proj_vs_mps, _x.vd_mps, _x.d_var, _x.vs_var,) = _get_struct_i8d().unpack(str[start:end])
        self.oppwpnts.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_dB = None
def _get_struct_dB():
    global _struct_dB
    if _struct_dB is None:
        _struct_dB = struct.Struct("<dB")
    return _struct_dB
_struct_i8d = None
def _get_struct_i8d():
    global _struct_i8d
    if _struct_i8d is None:
        _struct_i8d = struct.Struct("<i8d")
    return _struct_i8d
