// Generated by gencpp from file f110_msgs/CarState.msg
// DO NOT EDIT!


#ifndef F110_MSGS_MESSAGE_CARSTATE_H
#define F110_MSGS_MESSAGE_CARSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>

namespace f110_msgs
{
template <class ContainerAllocator>
struct CarState_
{
  typedef CarState_<ContainerAllocator> Type;

  CarState_()
    : slam_pose()
    , ekf_twist()  {
    }
  CarState_(const ContainerAllocator& _alloc)
    : slam_pose(_alloc)
    , ekf_twist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _slam_pose_type;
  _slam_pose_type slam_pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _ekf_twist_type;
  _ekf_twist_type ekf_twist;





  typedef boost::shared_ptr< ::f110_msgs::CarState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f110_msgs::CarState_<ContainerAllocator> const> ConstPtr;

}; // struct CarState_

typedef ::f110_msgs::CarState_<std::allocator<void> > CarState;

typedef boost::shared_ptr< ::f110_msgs::CarState > CarStatePtr;
typedef boost::shared_ptr< ::f110_msgs::CarState const> CarStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f110_msgs::CarState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f110_msgs::CarState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f110_msgs::CarState_<ContainerAllocator1> & lhs, const ::f110_msgs::CarState_<ContainerAllocator2> & rhs)
{
  return lhs.slam_pose == rhs.slam_pose &&
    lhs.ekf_twist == rhs.ekf_twist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f110_msgs::CarState_<ContainerAllocator1> & lhs, const ::f110_msgs::CarState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f110_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::CarState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::CarState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::CarState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::CarState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f110_msgs::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3b80f78749884a20d33b38f0c43c77";
  }

  static const char* value(const ::f110_msgs::CarState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3b80f78749884aULL;
  static const uint64_t static_value2 = 0x20d33b38f0c43c77ULL;
};

template<class ContainerAllocator>
struct DataType< ::f110_msgs::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f110_msgs/CarState";
  }

  static const char* value(const ::f110_msgs::CarState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f110_msgs::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose  slam_pose\n"
"geometry_msgs/Twist ekf_twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::f110_msgs::CarState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f110_msgs::CarState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.slam_pose);
      stream.next(m.ekf_twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f110_msgs::CarState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f110_msgs::CarState_<ContainerAllocator>& v)
  {
    s << indent << "slam_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.slam_pose);
    s << indent << "ekf_twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.ekf_twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F110_MSGS_MESSAGE_CARSTATE_H
