// Generated by gencpp from file f110_msgs/GapData.msg
// DO NOT EDIT!


#ifndef F110_MSGS_MESSAGE_GAPDATA_H
#define F110_MSGS_MESSAGE_GAPDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace f110_msgs
{
template <class ContainerAllocator>
struct GapData_
{
  typedef GapData_<ContainerAllocator> Type;

  GapData_()
    : header()
    , gap_diff(0.0)
    , vs_diff(0.0)
    , gap_int(0.0)  {
    }
  GapData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gap_diff(0.0)
    , vs_diff(0.0)
    , gap_int(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _gap_diff_type;
  _gap_diff_type gap_diff;

   typedef double _vs_diff_type;
  _vs_diff_type vs_diff;

   typedef double _gap_int_type;
  _gap_int_type gap_int;





  typedef boost::shared_ptr< ::f110_msgs::GapData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f110_msgs::GapData_<ContainerAllocator> const> ConstPtr;

}; // struct GapData_

typedef ::f110_msgs::GapData_<std::allocator<void> > GapData;

typedef boost::shared_ptr< ::f110_msgs::GapData > GapDataPtr;
typedef boost::shared_ptr< ::f110_msgs::GapData const> GapDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f110_msgs::GapData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f110_msgs::GapData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f110_msgs::GapData_<ContainerAllocator1> & lhs, const ::f110_msgs::GapData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gap_diff == rhs.gap_diff &&
    lhs.vs_diff == rhs.vs_diff &&
    lhs.gap_int == rhs.gap_int;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f110_msgs::GapData_<ContainerAllocator1> & lhs, const ::f110_msgs::GapData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f110_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::GapData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::GapData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::GapData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::GapData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::GapData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::GapData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f110_msgs::GapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b407209058e30969cf7468c302c926f1";
  }

  static const char* value(const ::f110_msgs::GapData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb407209058e30969ULL;
  static const uint64_t static_value2 = 0xcf7468c302c926f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::f110_msgs::GapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f110_msgs/GapData";
  }

  static const char* value(const ::f110_msgs::GapData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f110_msgs::GapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64 gap_diff\n"
"float64 vs_diff\n"
"float64 gap_int \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::f110_msgs::GapData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f110_msgs::GapData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gap_diff);
      stream.next(m.vs_diff);
      stream.next(m.gap_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GapData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f110_msgs::GapData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f110_msgs::GapData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gap_diff: ";
    Printer<double>::stream(s, indent + "  ", v.gap_diff);
    s << indent << "vs_diff: ";
    Printer<double>::stream(s, indent + "  ", v.vs_diff);
    s << indent << "gap_int: ";
    Printer<double>::stream(s, indent + "  ", v.gap_int);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F110_MSGS_MESSAGE_GAPDATA_H
