// Generated by gencpp from file f110_msgs/OpponentTrajectory.msg
// DO NOT EDIT!


#ifndef F110_MSGS_MESSAGE_OPPONENTTRAJECTORY_H
#define F110_MSGS_MESSAGE_OPPONENTTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <f110_msgs/OppWpnt.h>

namespace f110_msgs
{
template <class ContainerAllocator>
struct OpponentTrajectory_
{
  typedef OpponentTrajectory_<ContainerAllocator> Type;

  OpponentTrajectory_()
    : header()
    , lap_count(0.0)
    , opp_is_on_trajectory(false)
    , oppwpnts()  {
    }
  OpponentTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lap_count(0.0)
    , opp_is_on_trajectory(false)
    , oppwpnts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _lap_count_type;
  _lap_count_type lap_count;

   typedef uint8_t _opp_is_on_trajectory_type;
  _opp_is_on_trajectory_type opp_is_on_trajectory;

   typedef std::vector< ::f110_msgs::OppWpnt_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::f110_msgs::OppWpnt_<ContainerAllocator> >> _oppwpnts_type;
  _oppwpnts_type oppwpnts;





  typedef boost::shared_ptr< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct OpponentTrajectory_

typedef ::f110_msgs::OpponentTrajectory_<std::allocator<void> > OpponentTrajectory;

typedef boost::shared_ptr< ::f110_msgs::OpponentTrajectory > OpponentTrajectoryPtr;
typedef boost::shared_ptr< ::f110_msgs::OpponentTrajectory const> OpponentTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f110_msgs::OpponentTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f110_msgs::OpponentTrajectory_<ContainerAllocator1> & lhs, const ::f110_msgs::OpponentTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lap_count == rhs.lap_count &&
    lhs.opp_is_on_trajectory == rhs.opp_is_on_trajectory &&
    lhs.oppwpnts == rhs.oppwpnts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f110_msgs::OpponentTrajectory_<ContainerAllocator1> & lhs, const ::f110_msgs::OpponentTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f110_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe4d653bec85c82c41a017b9bdc2a6f1";
  }

  static const char* value(const ::f110_msgs::OpponentTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe4d653bec85c82cULL;
  static const uint64_t static_value2 = 0x41a017b9bdc2a6f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f110_msgs/OpponentTrajectory";
  }

  static const char* value(const ::f110_msgs::OpponentTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 lap_count\n"
"bool opp_is_on_trajectory\n"
"OppWpnt[] oppwpnts\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: f110_msgs/OppWpnt\n"
"int32 id\n"
"\n"
"# frenet coordinates\n"
"float64 s_m\n"
"float64 d_m\n"
"\n"
"# map coordinates\n"
"float64 x_m\n"
"float64 y_m\n"
"\n"
"# track information\n"
"float64 proj_vs_mps\n"
"float64 vd_mps\n"
"\n"
"#variance  \n"
"float64 d_var\n"
"float64 vs_var\n"
"\n"
;
  }

  static const char* value(const ::f110_msgs::OpponentTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lap_count);
      stream.next(m.opp_is_on_trajectory);
      stream.next(m.oppwpnts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpponentTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f110_msgs::OpponentTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f110_msgs::OpponentTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lap_count: ";
    Printer<double>::stream(s, indent + "  ", v.lap_count);
    s << indent << "opp_is_on_trajectory: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.opp_is_on_trajectory);
    s << indent << "oppwpnts[]" << std::endl;
    for (size_t i = 0; i < v.oppwpnts.size(); ++i)
    {
      s << indent << "  oppwpnts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::f110_msgs::OppWpnt_<ContainerAllocator> >::stream(s, indent + "    ", v.oppwpnts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // F110_MSGS_MESSAGE_OPPONENTTRAJECTORY_H
