// Generated by gencpp from file f110_msgs/OppWpnt.msg
// DO NOT EDIT!


#ifndef F110_MSGS_MESSAGE_OPPWPNT_H
#define F110_MSGS_MESSAGE_OPPWPNT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace f110_msgs
{
template <class ContainerAllocator>
struct OppWpnt_
{
  typedef OppWpnt_<ContainerAllocator> Type;

  OppWpnt_()
    : id(0)
    , s_m(0.0)
    , d_m(0.0)
    , x_m(0.0)
    , y_m(0.0)
    , proj_vs_mps(0.0)
    , vd_mps(0.0)
    , d_var(0.0)
    , vs_var(0.0)  {
    }
  OppWpnt_(const ContainerAllocator& _alloc)
    : id(0)
    , s_m(0.0)
    , d_m(0.0)
    , x_m(0.0)
    , y_m(0.0)
    , proj_vs_mps(0.0)
    , vd_mps(0.0)
    , d_var(0.0)
    , vs_var(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef double _s_m_type;
  _s_m_type s_m;

   typedef double _d_m_type;
  _d_m_type d_m;

   typedef double _x_m_type;
  _x_m_type x_m;

   typedef double _y_m_type;
  _y_m_type y_m;

   typedef double _proj_vs_mps_type;
  _proj_vs_mps_type proj_vs_mps;

   typedef double _vd_mps_type;
  _vd_mps_type vd_mps;

   typedef double _d_var_type;
  _d_var_type d_var;

   typedef double _vs_var_type;
  _vs_var_type vs_var;





  typedef boost::shared_ptr< ::f110_msgs::OppWpnt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f110_msgs::OppWpnt_<ContainerAllocator> const> ConstPtr;

}; // struct OppWpnt_

typedef ::f110_msgs::OppWpnt_<std::allocator<void> > OppWpnt;

typedef boost::shared_ptr< ::f110_msgs::OppWpnt > OppWpntPtr;
typedef boost::shared_ptr< ::f110_msgs::OppWpnt const> OppWpntConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f110_msgs::OppWpnt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f110_msgs::OppWpnt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f110_msgs::OppWpnt_<ContainerAllocator1> & lhs, const ::f110_msgs::OppWpnt_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.s_m == rhs.s_m &&
    lhs.d_m == rhs.d_m &&
    lhs.x_m == rhs.x_m &&
    lhs.y_m == rhs.y_m &&
    lhs.proj_vs_mps == rhs.proj_vs_mps &&
    lhs.vd_mps == rhs.vd_mps &&
    lhs.d_var == rhs.d_var &&
    lhs.vs_var == rhs.vs_var;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f110_msgs::OppWpnt_<ContainerAllocator1> & lhs, const ::f110_msgs::OppWpnt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f110_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::OppWpnt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::OppWpnt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::OppWpnt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::OppWpnt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::OppWpnt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::OppWpnt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f110_msgs::OppWpnt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81351e4053edb61a279791df3b5554d5";
  }

  static const char* value(const ::f110_msgs::OppWpnt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81351e4053edb61aULL;
  static const uint64_t static_value2 = 0x279791df3b5554d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::f110_msgs::OppWpnt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f110_msgs/OppWpnt";
  }

  static const char* value(const ::f110_msgs::OppWpnt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f110_msgs::OppWpnt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"\n"
"# frenet coordinates\n"
"float64 s_m\n"
"float64 d_m\n"
"\n"
"# map coordinates\n"
"float64 x_m\n"
"float64 y_m\n"
"\n"
"# track information\n"
"float64 proj_vs_mps\n"
"float64 vd_mps\n"
"\n"
"#variance  \n"
"float64 d_var\n"
"float64 vs_var\n"
"\n"
;
  }

  static const char* value(const ::f110_msgs::OppWpnt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f110_msgs::OppWpnt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.s_m);
      stream.next(m.d_m);
      stream.next(m.x_m);
      stream.next(m.y_m);
      stream.next(m.proj_vs_mps);
      stream.next(m.vd_mps);
      stream.next(m.d_var);
      stream.next(m.vs_var);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OppWpnt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f110_msgs::OppWpnt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f110_msgs::OppWpnt_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "s_m: ";
    Printer<double>::stream(s, indent + "  ", v.s_m);
    s << indent << "d_m: ";
    Printer<double>::stream(s, indent + "  ", v.d_m);
    s << indent << "x_m: ";
    Printer<double>::stream(s, indent + "  ", v.x_m);
    s << indent << "y_m: ";
    Printer<double>::stream(s, indent + "  ", v.y_m);
    s << indent << "proj_vs_mps: ";
    Printer<double>::stream(s, indent + "  ", v.proj_vs_mps);
    s << indent << "vd_mps: ";
    Printer<double>::stream(s, indent + "  ", v.vd_mps);
    s << indent << "d_var: ";
    Printer<double>::stream(s, indent + "  ", v.d_var);
    s << indent << "vs_var: ";
    Printer<double>::stream(s, indent + "  ", v.vs_var);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F110_MSGS_MESSAGE_OPPWPNT_H
