// Generated by gencpp from file f110_msgs/PidData.msg
// DO NOT EDIT!


#ifndef F110_MSGS_MESSAGE_PIDDATA_H
#define F110_MSGS_MESSAGE_PIDDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace f110_msgs
{
template <class ContainerAllocator>
struct PidData_
{
  typedef PidData_<ContainerAllocator> Type;

  PidData_()
    : header()
    , should(0.0)
    , actual(0.0)
    , error(0.0)
    , d_value(0.0)
    , i_value(0.0)
    , input(0.0)  {
    }
  PidData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , should(0.0)
    , actual(0.0)
    , error(0.0)
    , d_value(0.0)
    , i_value(0.0)
    , input(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _should_type;
  _should_type should;

   typedef double _actual_type;
  _actual_type actual;

   typedef double _error_type;
  _error_type error;

   typedef double _d_value_type;
  _d_value_type d_value;

   typedef double _i_value_type;
  _i_value_type i_value;

   typedef double _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::f110_msgs::PidData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f110_msgs::PidData_<ContainerAllocator> const> ConstPtr;

}; // struct PidData_

typedef ::f110_msgs::PidData_<std::allocator<void> > PidData;

typedef boost::shared_ptr< ::f110_msgs::PidData > PidDataPtr;
typedef boost::shared_ptr< ::f110_msgs::PidData const> PidDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f110_msgs::PidData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f110_msgs::PidData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f110_msgs::PidData_<ContainerAllocator1> & lhs, const ::f110_msgs::PidData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.should == rhs.should &&
    lhs.actual == rhs.actual &&
    lhs.error == rhs.error &&
    lhs.d_value == rhs.d_value &&
    lhs.i_value == rhs.i_value &&
    lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f110_msgs::PidData_<ContainerAllocator1> & lhs, const ::f110_msgs::PidData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f110_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::PidData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::PidData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::PidData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::PidData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::PidData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::PidData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f110_msgs::PidData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06660779b958c3109e9e68b5c0a7b096";
  }

  static const char* value(const ::f110_msgs::PidData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06660779b958c310ULL;
  static const uint64_t static_value2 = 0x9e9e68b5c0a7b096ULL;
};

template<class ContainerAllocator>
struct DataType< ::f110_msgs::PidData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f110_msgs/PidData";
  }

  static const char* value(const ::f110_msgs::PidData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f110_msgs::PidData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64 should\n"
"float64 actual\n"
"float64 error\n"
"float64 d_value\n"
"float64 i_value\n"
"float64 input\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::f110_msgs::PidData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f110_msgs::PidData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.should);
      stream.next(m.actual);
      stream.next(m.error);
      stream.next(m.d_value);
      stream.next(m.i_value);
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PidData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f110_msgs::PidData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f110_msgs::PidData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "should: ";
    Printer<double>::stream(s, indent + "  ", v.should);
    s << indent << "actual: ";
    Printer<double>::stream(s, indent + "  ", v.actual);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "d_value: ";
    Printer<double>::stream(s, indent + "  ", v.d_value);
    s << indent << "i_value: ";
    Printer<double>::stream(s, indent + "  ", v.i_value);
    s << indent << "input: ";
    Printer<double>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F110_MSGS_MESSAGE_PIDDATA_H
